### ISSUE TITLE
New Expansions up to Prophetic Visions for RAA.

### ISSUE THREAD

**Issue by jtrpka0912** [jtrussell/sloppy-labwork#24]
With the (mass) release of new sets (AES, ToC, and MoreM); I present the necessary code to update the Random Access Archive.

```
(800, _('Æmber Skies')),
(855, _('Tokens of Change')),
(874, _('More Mutation')),
```

Granted, there are three comment out sets, but these can be in the code for later updates or not added entirely.

**Comment by jtrussell** [comment]
Thanks @jtrpka0912! It might be time to move these to the DB soon 😂. Want to remove the commented out lines and then we'll get this merged?

**Comment by jtrpka0912** [comment]
Code updated without the comment out lines.

Having the set/expansions be in a database might be more suitable in the long run.

**Comment by jtrussell** [comment]
Sorry, for some reason I thought this was a PR 😅. Site's been updated with those sets and I'll be updating the Discord bot shortly too 👍 .
